Hw №1, bot module
Nick-552/link-tracker pull request #1
Opened 2024-02-18 20:17 UTC by Nick-552

2024-02-19 20:22 UTC, SHvatov requested changes
@Nick-552 и снова здравствуй! Я снова буду проверять твои домашки)

Оставил комментарии, посмотри их, пожалуйста. Еще я создал небольшую группу в телеге для всяких анонсов, чисто для тех, кто в моей группе - https://t.me/+KoDhaQZiHokwNDcy.

2024-02-19 20:22 UTC, SHvatov commented on bot/src/test/java/edu/java/bot/handler/handlers/terminating/commands/HelpUpdateHandlerTest.java
> +class HelpUpdateHandlerTest {
1. Чего-то бот с покрытием поехал, хорошо бы глянуть почему 0 везде)
2. Тестиков бы еще, пока классы простые советую набить покрытие по-максимуму)

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/bot/Bot.java
> +    int process(List<Update> updates);
Чего-то во всех работах я вижу этот интерфейс. Он у вас из шаблона что ли? Как думаешь, он необходим, или от него можно избавиться?

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +    private final ApplicationConfig config;
К идее стоит прислушиваться, она дурного не посоветует)

![image](https://github.com/Nick-552/link-tracker/assets/15994914/97bd5827-47f8-4ec3-8300-a9453982b906)

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +                AbstractSendRequest sendRequest = userMessageProcessor.process(update);
ой, unchecked cast... Можем от него как-нибудь избавиться?

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    public static UserLinksStorageService storage() {
Давай бином? Это же те же самые синглтоны, только они менеджатся контейнером, и таких приседаний делать не надо)

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    public static String about() {
Вот это бы я вынес просто в утильный класс с константами, конфиги больше про конфигурацию приложения / бинов.

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/Command.java
> +    public String command() {
`@Getter`

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/HandlerUtils.java
> +public class HandlerUtils {
Давай на два класса разобьем, будет чуть полегче с ним работать. А то такой ультимативный класс получается.

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/handlers/continuing/UpdateHandlerContinuing.java
> +public abstract class UpdateHandlerContinuing extends UpdateHandlerWithNext {
Скажу честно, иерархия получилась сложноватой) Попробуем ее упростить?

![image](https://github.com/Nick-552/link-tracker/assets/15994914/a0701de5-f184-4076-a9ae-47fbeb3c4023)

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/handlers/continuing/UpdateHandlerContinuing.java
> +    public AbstractSendRequest handle(Update update) {
`AbstractSendRequest` -> `SendMessage` и минус все unchecked_cast ворнинги. В данном случае лучше пренебречь LSP в пользу читаемости.

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/handlers/terminating/commands/TrackUpdateHandler.java
> +        var user = HandlerUtils.user(update);
Декомпозировать не получится?

2024-02-19 20:22 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/handlers/terminating/commands/TrackUpdateHandler.java
> +        return url.startsWith("https://") || url.startsWith("http://");
Хорошо бы в константы

2024-02-19 20:43 UTC, Nick-552 commented on bot/src/test/java/edu/java/bot/handler/handlers/terminating/commands/HelpUpdateHandlerTest.java
> +class HelpUpdateHandlerTest {
Бот поехал, потому что покрытие тестами отдельно для модуля бота и модуля скраппера считаются отдельно, при этом выводится последний из них. Видимо из за того что изменения были не только в модуле бота, он скраппер тоже считает. Там можно раскрыть по стрелочке, где написано edited на комменте PR от бота и будут видны другие проверки покрытия.
Тестики допишу еще

2024-02-19 20:44 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/bot/Bot.java
> +    int process(List<Update> updates);
Да, был в шаблоне. Судя по тому, что у нас не предполагается разных реализаций бота, он не особо нужен.

2024-02-19 20:59 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +                AbstractSendRequest sendRequest = userMessageProcessor.process(update);
Вообще у меня пока что там только `SendMessage` передается, но я хотел бы, чтобы можно было и другое, поэтому  изменил `SendMessage` на `AbstractSendRequest`. Исправил на `AbstractSendRequest<? extends AbstractSendRequest<?>>`, теперь идейка не ругается на raw type

2024-02-19 21:15 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +    private final ApplicationConfig config;
Поправил

2024-02-19 21:39 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/handler/handlers/continuing/UpdateHandlerContinuing.java
> +    public AbstractSendRequest handle(Update update) {
Хочется оставить возможность отсылать что-то кроме SendMessage

2024-02-19 21:49 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/handler/HandlerUtils.java
> +public class HandlerUtils {
Разбил на `HandlerMessages`, куда запихнул все текстовые константы для отправки сообщений, и `HandlerUtils`, где остались методы, помогающие в обработке `update`ов

2024-02-19 22:33 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/handler/handlers/continuing/UpdateHandlerContinuing.java
> +public abstract class UpdateHandlerContinuing extends UpdateHandlerWithNext {
Избавился от разделения на continuing и terminating, добавив логику, завязанную на Optional

2024-02-19 22:35 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/handler/handlers/terminating/commands/TrackUpdateHandler.java
> +        return url.startsWith("https://") || url.startsWith("http://");
Вынес метод в отдельный класс LinkUtils, который будет проверять ссылки, и вынес строки в константы

2024-02-19 23:09 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    public static UserLinksStorageService storage() {
Имеется в виду накинуть просто аннотацию `@Bean` на метод? Метод при этом нужно оставить `static`? Если нет, то как тогда инжектить его в хэндлеры? 
Я в спринге совсем новичок и не очень понимаю, как всё правильно сделать.

2024-02-19 23:10 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    public static String about() {
Сделал

2024-02-20 23:09 UTC, Nick-552 commented
Внес предложенные изменения, дописал тесты на большую часть классов.

2024-02-24 12:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    public static UserLinksStorageService storage() {
Во-первых, по спрингу советовал бы глянуть вот эти статьи для начала по бинам:
- https://www.baeldung.com/spring-bean
- https://www.baeldung.com/spring-bean-annotations
Вообще, основной компонент спринга, за который его все любят - Spring DI. DI в данном случае - dependency injection (и заодно management). У тебя каждый бин - это уже синглтон, который управляется спрингом. В том числе фреймворк ответственен за то, чтобы этот бин вставлять в другие бины, если те являются бинами. Метод статичным сделать нельзя, нужно как в статье либо пометить `UserLinksStorageService` как `@Service/@Component`, либо же создать конфигурационный бин (класс, помеченный как `@Configuration`) и в нем объявить метод, помеченный как @Bean, в котором будет создаваться этот сервис.

2024-02-24 12:57 UTC, SHvatov requested changes
@Nick-552 посмотри коммент про бины, а в остальном 👌

2024-02-24 22:54 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    public static UserLinksStorageService storage() {
Спасибо за интересные статьи. Они явно улучшили моё понимание того, как работают бины. Моей основной проблемой, как оказалось, была архитектура, в некоторых местах оказавшаяся довольно неудобной для того чтобы инжектить бины. Например, не очень удобно инжектить бины в поле Enum.
Поправил код:
Теперь в классе `ApplicationConfig` находится метод помеченный `@Bean`, создающий `InMemoryUserLinksStorageService`. 
Также создал новый класс - `HandlerProvider`, куда инжектится `InMemoryUserLinksStorageService`.
Этот класс также является бином и предназначен для предоставления объектов типа `Handler`.
Надеюсь, что теперь всё правильно)
_____________________________________
О, сколько нам открытий чудных
Готовят просвещенья дух,
И опыт, сын ошибок трудных,
И гений, парадоксов друг

2024-02-24 23:00 UTC, Nick-552 commented
Поправил бины

2024-02-25 17:02 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    public static UserLinksStorageService storage() {
Я рад, что помог :) Будут вопросы - пиши!

2024-02-25 17:04 UTC, SHvatov approved these changes
@Nick-552 🔥, можно 🚀

2024-02-25 17:05 UTC, merged