HW №2, scrapper module
Nick-552/link-tracker pull request #2
Opened 2024-02-24 21:32 UTC by Nick-552

2024-02-26 18:27 UTC, SHvatov requested changes
@Nick-552 оставил пару комментариев, погляди их, пожалуйста.

2024-02-26 18:27 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +    protected static final String BASE_URL = "https://api.github.com";
Такие литералы лучше держать на уровне конфигурации, даже если это дефолтное значение. https://www.baeldung.com/spring-value-defaults. Там еще и вот такая штука теперь есть - https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/context/properties/bind/DefaultValue.html.

2024-02-26 18:27 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +    public LastLinkUpdate getLastUpdate(String url) {
Тут возникает холиварный вопрос, а кто должен отвечать за вычленение инфы о репозитории из урла. Я бы в клиенте оставил только второй метод, и убрал бы наследование от `LinkUpdatesClient`. 

Это, конечно, ИМХО, но клиенты - чисто про выполнение запросов. А теперь тут еще логика по парсингу урлов для выполнения этих самых запросов. А если захотим не только репки, но пользаков отслеживать? Метод будет только расти, в нем будут новые if'ы...

2024-02-26 18:27 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +            .onErrorReturn(new GithubRepoInfo(null, null))
Вот это не очень хорошее решение - лучше пусть кидает исключение, а вызывающий код его обрабатывает. Легко можно будет проворонить и 400-ку, которая говорит нам о том, что запрос делаем с неправильными параметрами, и 429, которая говорит нам о превышении рейт-лимитера.

2024-02-26 18:27 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +    public record GithubRepoInfo(
DTO лучше в пакет отедльный вынести.

2024-02-27 12:05 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +    protected static final String BASE_URL = "https://api.github.com";
Перенес в application.yml

2024-02-27 12:06 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +            .onErrorReturn(new GithubRepoInfo(null, null))
Теперь кидает исключение

2024-02-27 12:06 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +    public record GithubRepoInfo(
Вынес

2024-02-27 12:18 UTC, Nick-552 commented
Чуть чуть порефакторил код исходя из замечаний, также добавил возможность создания `GithubClient` с авторизованными запросами: при создании бина `GithubClient` если заполнен токен авторизации (api-client.github.auth-token) то будет проведена проверка на правильность токена и, в зависимости от результата, создан или `GithubClient` c `defaultHeader` авторизации или без.

2024-02-28 13:17 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +    public LastLinkUpdate getLastUpdate(String url) {
`JSONObject` это хорошо, но там под капотом у клиентов уже есть десериализаторы. Сейчас как получается - тебе приходят байтики, ты конвертишь их в строку, из строки в JSON, из JSON - в нужную тебе ДТО. Выглядит немного избыточно, не находишь? Я писал про то, что хорошо бы разделять клиенты и бизнес логику, которая эти клиенты использует.

2024-02-28 13:18 UTC, SHvatov commented on .gitignore
> +**/secrets.*
ой, секретные материалы подъехали)

2024-02-28 13:18 UTC, SHvatov requested changes
@Nick-552 про JSON отписался, посмотри, пожалуйста.

2024-02-28 20:32 UTC, Nick-552 commented on .gitignore
> +**/secrets.*
Токен для авторизации github, без него 60 запросов в час😔, а с ним 5000😃

2024-02-29 14:56 UTC, Nick-552 commented
внес изменения

2024-02-29 19:06 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +    public LastLinkUpdate getLastUpdate(String url) {
Хм, если рассуждать так, то да, выглядит немного монструозно и мы стараемся таким не промышлять. Но такое случается достаточно редко - мало кто передает так много инфы. Если здесь есть такая проблема, то ок, давай оставим JSON. Но вроде бы это не тот кейс.

2024-02-29 19:06 UTC, SHvatov approved these changes
@Nick-552 🔥, можно мержить!

2024-02-29 19:22 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/client/github/GithubClient.java
> +    public LastLinkUpdate getLastUpdate(String url) {
Понял, спасибо за ответ.

2024-02-29 19:36 UTC, merged