Hw3
Nick-552/link-tracker pull request #3
Opened 2024-03-03 20:50 UTC by Nick-552

2024-03-05 20:27 UTC, SHvatov commented
@Nick-552 покрытие, конечно, рухнуло знатно) Может есть что-нибудь еще, что можно покрыть тестами?

2024-03-05 20:41 UTC, SHvatov requested changes
@Nick-552 оставил комментарии, посмотри их, пожалуйста.

2024-03-05 20:41 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/client/scrapper/scrapper/ScrapperClient.java
> +                if (clientResponse.statusCode().is2xxSuccessful()) {
1. Стоит разбить на is2xx и ошибки, ошибки можно обрабатывать с помощью `onStatus`, который еще и можно вынести в общий компонент и везде переиспользовать - https://stackoverflow.com/questions/56015154/how-to-handle-standard-status-with-spring-webclient
2. Оборачивая в RuntimeException ты теряешь очень много полезной инфы - статус, к примеру. Он тебе равзе не нужен для формирования `ApiErrorResponse`?

2024-03-05 20:41 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/client/scrapper/scrapper/ScrapperClient.java
> +                if (clientResponse.statusCode().is2xxSuccessful()) {
3. С маппингом ответа в `ApiErrorResponse` возникают ненужные касты. Почему бы не пробовать смапить любой ответ в `ApiErrorResponse`, и если получится - кидать какой-нибудь `ApiException`, а если нет - его наследника `UnknownApiException`?

2024-03-05 20:41 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/client/scrapper/scrapper/ScrapperClient.java
> +                if (clientResponse.statusCode().is2xxSuccessful()) {
4. Вообще вся связка `exchangeToMono ->  instanceof ApiErrorResponse -> (Response) response` повторяется во всех методах. В любом случае стоит попробовать унифицировать.

2024-03-05 20:41 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/controller/LinkUpdatesController.java
> +    public LinkUpdatesController(LinkUpdateNotificationService notificationService) {
`RequiredArgsConstructor`?

2024-03-05 20:41 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/controller/advice/ExceptionApiHandler.java
> +    @ExceptionHandler(Exception.class)
Не совсем корректный обработчик - те же 500ки тоже сюда прилетят, а ты в них напишешь, что данные некорректные. Хотя у тебя просто скраппер лежит, к примеру.

2024-03-05 20:41 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/AbstractGetJsonWebClient.java
> +    public <T> T getResponse(String uri, Class<T> tClass) {
А чем обычный AbstractJsonWebClient не устроил? А что если нужен будет post? Создашь еще один клиент 😄 ?

2024-03-05 20:41 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/bot/BotClient.java
> +        @Value("${api.bot.base-url:http://localhost:8090}") String baseUrl
Такие дефолтные значения лучше держать на уровне конфига. Часто, для разработки, их вообще уносят в local.env файлы и используют вот такой плагин для запуска локально - https://plugins.jetbrains.com/plugin/7861-envfile. Еще один довод в пользу - так легко забыть прописать значение в конфиге, а потом на проде словить ошибки из-за того, что сервис посылает запросы на локалку.

2024-03-05 20:41 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/bot/request/LinkUpdate.java
> +    @NotNull Long id,
Это же ДТОха для запроса. Кто будет ее валидировать?

2024-03-05 20:41 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/controller/TgChatController.java
> +    public void deleteChat(@PathVariable Long id) {
Вот тут можно докинуть валидаций на число)

2024-03-05 20:41 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/controller/advice/ApiErrorHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
80% каждого метода одинаковы.

2024-03-05 20:41 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/exception/ApiException.java
> +    private final HttpStatus httpStatus;
О, вот как раз про это я и говорю. Хорошая собственная иерархия исключений для АПИ.

2024-03-05 20:41 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/LinksService.java
> +    public static LinkResponse createLinkResponseWithId(Long id) {
Это мок? Может его на уровень репозитория унести?

2024-03-07 07:40 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/client/AbstractGetJsonWebClient.java
> +    public <T> T getResponse(String uri, Class<T> tClass) {
У меня изначально были два клиента для github api и stackoverflow api. У них обоих был одинаковый GET метод, который я решил вынести в абстрактный класс. Потом я понял что это не очень удобно, потому что у каждого клиента могут быть свои методы, и лучше их разделять, поэтому сделал просто AbstractJsonWebClient без метода GET, а старый класс пока не удалял, раз уж он уже написан. Но я так понял, что это не лучшая практика, поэтому убрал его сейчас.

2024-03-07 07:51 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/client/bot/BotClient.java
> +        @Value("${api.bot.base-url:http://localhost:8090}") String baseUrl
Следует ли туда то же самое сделать с tg token и github auth token?

2024-03-07 09:27 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/controller/TgChatController.java
> +    public void deleteChat(@PathVariable Long id) {
А какие тут будут валидации? просто если там придет строка вместо числа то будет 
![image](https://github.com/Nick-552/link-tracker/assets/115263760/5f9d23b5-ce4c-4b59-813f-1e15dfb81deb)
Если будет /tg-chat/ или /tg-chat// то будет просто not found
![image](https://github.com/Nick-552/link-tracker/assets/115263760/61f2e4f6-87e6-4c71-ab68-eac44a25fc4f)
Насчет отрицательных чисел я не уверен, что не  может быть отрицательных id у чатов.

2024-03-07 09:38 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/controller/TgChatController.java
> +    public void deleteChat(@PathVariable Long id) {
На stackoverflow пишут что chat id положительные для обычных чатов и отрицательные для групповых, но никаких других подтверждений этому я не нашел.
По крайней мере, добавив валидацию на неотрицательность мы обрубим себе групповые чаты

2024-03-07 11:47 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/service/LinksService.java
> +    public static LinkResponse createLinkResponseWithId(Long id) {
ну это просто заглушка, чтобы хоть что то возвращало, она будет удалена впоследствии.

2024-03-07 11:48 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/client/bot/request/LinkUpdate.java
> +    @NotNull Long id,
Убрал аннотации

2024-03-07 12:25 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/client/bot/request/LinkUpdate.java
> +    @NotNull Long id,
Убрал аннотации

2024-03-07 21:48 UTC, Nick-552 commented
Внес предложенные изменения.
Надеюсь, в этот раз клиенты нормальные, потому что иначе я уже не знаю как🙃.
TODO: написать тесты

2024-03-11 20:19 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/controller/TgChatController.java
> +    public void deleteChat(@PathVariable Long id) {
Хм, если это так, то ок. Но это очень интересный момент.

2024-03-11 20:20 UTC, SHvatov approved these changes
@Nick-552 👌, можно мержить.

2024-03-11 20:41 UTC, Nick-552 commented
> > Надеюсь, в этот раз клиенты нормальные, потому что иначе я уже не знаю как
> 
> Клиенты и до этого были норм, просто больно специфичные, из-за чего абстрактными их язык не поворачивался назвать)

Я про обработку тех случаев, когда нам приходит не 200 а 4хх или 5хх и нам вместо ожидаемого ответа нужно обработать ApiErrorResponse.

А насчет абстрактности клиентов, конкретными их тоже сложно назвать:
Один вообще не имеет никаких методов вызывающих http запросы, просто добавляет хедеры при создании.
Другой имеет 1 метод, который выполняет get запрос по любому переданному url и мапит ответ в объект переданного класса. Да и не является бином и не создается с определенным base_url.

2024-03-12 15:02 UTC, merged