Выполнена домашняя работа №5
Nick-552/link-tracker pull request #5
Opened 2024-03-15 20:23 UTC by Nick-552

2024-03-17 21:29 UTC, Nick-552 commented
![image](https://github.com/Nick-552/link-tracker/assets/115263760/a5a4906a-eb0e-4a14-ad84-ee69ee60dae1)
Наглядная демонстрация работы

2024-03-24 18:26 UTC, SHvatov commented
@Nick-552 отдельный респект и благодарность за такое детальное описание!

2024-03-25 05:53 UTC, SHvatov requested changes
@Nick-552 🔥, однако оставил пару комментариев. Посмотри их, пожалуйста.

2024-03-25 05:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +    public final String description = "С помощью этого бота вы можете отслеживать обновление контента на таких страницах, как stackoverflow и GitHub.";
Можно не суппрессить, а просто конкатенировать строки, или же использовать текстовые блоки.

2024-03-25 05:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +    public final String about = "Бот для отслеживания изменений на страницах";
И может сделать их константами?

2024-03-25 05:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/client/scrapper/ScrapperClient.java
> +            } catch (Exception e) {
А здесь откуда будет исключение?

2024-03-25 05:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/handlers/commands/ListUpdateHandler.java
> +                var linksList = links.links().stream().map(linkResponse -> linkResponse.url().toString()).toList();
`urls`, а то не понятно, в чем отличие между `links` и `linksList`)

2024-03-25 05:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/storage/ChatLinksStorage.java
> +public interface ChatLinksStorage {
В названиях репозиториев стараются не использовать множественное число, и давай заменим Storage на Repository?

2024-03-25 05:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/storage/ChatLinksStorage.java
> +public interface ChatLinksStorage {
Storage больше про хранлище, то есть я бы предположил, что у тебя там хранятся чаты. А на самом деле это клиент к БД.

2024-03-25 05:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/utils/MessagesUtils.java
> +    public static final String UPDATE = """
Стоит конкретизировать -  обновление чего?

2024-03-25 05:53 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/utils/MessagesUtils.java
> +    public static final String UPDATE = """
И как-то в классе все в разнобой идет. Давай приведем к какому-то единому формату / последовательности. Сначала константы, потом публинчые, потом приватные методы.

2024-03-25 05:53 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/repository/jdbc/ChatLinkRepository.java
> +    @Transactional
Про транзакционность писал в чатике

2024-03-25 05:53 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/repository/jdbc/LinkRepository.java
> +        if (jdbcClient.sql(SELECT_BY_URL).params(url.toString()).query(Link.class).list().isEmpty()) {
Оу ноу, так делать не надо - ты потом в случае отладки будешь себя очень за это корить) Лучше результат в переменную, и работать уже с ней. Да и выглядит страшненько такой длинный иф)

2024-03-25 05:53 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksService.java
> +    @Transactional
Мне больше импонирует, когда `@Transactional` в реализации, а не на уровне интерфейса. А то легко забыть, что он у тебя тут навешан. И точно ли на все нужны транзакции? И зачем интерфейс? Будет еще реализация?

2024-03-25 05:53 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksServiceJdbcImpl.java
> +public class LinksServiceJdbcImpl implements LinksService {
1. Держать в названии, что конкретно используется под капотом - избыточно. `LinksServiceWrittenInJavaWhichUsesJdbc` 😄 
2. Я бы сервис сделал один, а вот уже под капотом менял реализацию репозитория. Я более чем уверен, что не JDBC-ный сервис у тебя будет выглядеть ровно так же.

2024-03-25 05:53 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksServiceJdbcImpl.java
> +                throw new LinkNotFoundException();
На будущее - операции по удалению сущностей стараются делать идемпотентными. Ну нет сущности, ну и ладно, мы и так хотели ее удалить. Чего бухтеть-то?)

2024-03-25 06:02 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksServiceJdbcImpl.java
> +public class LinksServiceJdbcImpl implements LinksService {
Будешь смеяться, но в задании написано сделать jdbc реализацию сервиса.
В 5 доп переделал на реализацию которая использует интерфейсы репозитория (она общая для жука и jdbc), не уверен, что jpa так же получится прикрутить, поэтому и сделал интерфейсы сервиса.

2024-03-25 07:16 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/repository/jdbc/ChatLinkRepository.java
> +    @Transactional
Убрал `@Transactional` из классов репозиториев

2024-03-25 07:20 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksService.java
> +    @Transactional
Перенес `Transactional` в реализацию

2024-03-25 07:24 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksServiceJdbcImpl.java
> +public class LinksServiceJdbcImpl implements LinksService {
Насчет наименований не особо понял, как лучше именовать? Мне же нужно различать имплементации как то. Я подумал, что указать, на чем реализована имплементация, будет хорошей идеей.

2024-03-25 07:32 UTC, Nick-552 commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksServiceJdbcImpl.java
> +                throw new LinkNotFoundException();
В данном случае запрос на удаление ссылки приходит со стороны пользователя. Не хочется его обманывать, говоря, что ссылка была успешно удалена.
Вдруг он хотел удалить 2 ссылки, но случайно написал одну и ту же 2 раза, а я ему скажу, что он молодец и всё хорошо.

2024-03-25 07:45 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +    public final String about = "Бот для отслеживания изменений на страницах";
Вынес в конфиг

2024-03-25 07:48 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +    public final String description = "С помощью этого бота вы можете отслеживать обновление контента на таких страницах, как stackoverflow и GitHub.";
Если в текстовом блоке будет длинная строка, то там checkstyle тоже будет ругаться, при разбитии на две строки добавится `\n`. Конкатенация тоже не очень красиво выглядит.
Посчитал излишним разбивать как то строку, состоящую из 1 предложения, только чтобы угодить checkstyle.

2024-03-25 07:51 UTC, Nick-552 commented on bot/src/main/java/edu/java/bot/client/scrapper/ScrapperClient.java
> +            } catch (Exception e) {
Ниоткуда. 
Вообще цель была обработать случай, когда лежит скраппер и выбрасывается исключение с connection refused, но я уже понял, что так его не поймать, а убрать try catch забыл.

2024-03-27 12:56 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/bot/LinkTrackerBot.java
> +    public final String description = "С помощью этого бота вы можете отслеживать обновление контента на таких страницах, как stackoverflow и GitHub.";
ну ок....

2024-03-27 12:57 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksServiceJdbcImpl.java
> +public class LinksServiceJdbcImpl implements LinksService {
> В 5 доп переделал на реализацию которая использует интерфейсы репозитория

вот этого я и хотел)

2024-03-27 12:58 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/links/LinksServiceJdbcImpl.java
> +                throw new LinkNotFoundException();
хм, смотри, перехвалишь пользователя, они разнежатся, и когда-нибудь, когда ты их не похвалишь, будут очень злы на тебя...

2024-03-27 12:58 UTC, SHvatov approved these changes
@Nick-552 🔥, 🚀

2024-03-28 07:54 UTC, merged