Домашняя работа №8
Nick-552/link-tracker pull request #9
Opened 2024-04-07 15:51 UTC by Nick-552

# Выполнена домашняя работа №8

В compose файл добавлены сервисы kafka и zookeeper
Для каждого из них добавлены volumes

![image](https://github.com/Nick-552/link-tracker/assets/115263760/29c02e63-806f-4cb4-88fb-6742e920922a)

Созданы необходимые бины для Kafka

Написан класс-сервис для отправки сообщений об обновлении ссылок через Kafka в модуле scrapper.

Добавлен параметр useQueue для выбора способа отправки (Kafka или HTTP WebClient).

Написан KafkaListener-класс для получения и обработки сообщений об обновлении ссылок.

Добавлен Kafka-топик c суффиксом _dlq в который отправляются сообщения об обновлении которые не могут быть обработаны или обработка которых вызвала ошибку.

2024-04-09 11:41 UTC, Nick-552 commented
Есть вопрос по поводу KafkaListener:
Должны ли мы как то обрабатывать сообщения для которых возникла ошибка десериализации?
Нужно ли их складывать в _dlq?
И если да, то предоставляет ли кафка и спринг готовое решение для этого?

2024-04-14 14:38 UTC, SHvatov commented
> Должны ли мы как то обрабатывать сообщения для которых возникла ошибка десериализации?
Нужно ли их складывать в _dlq?
И если да, то предоставляет ли кафка и спринг готовое решение для этого?

Да, можно почитать вот эту статью - https://www.baeldung.com/spring-kafka-deserialization-errors. 

> Принято ли делать на KafkaListener retry политику (то есть когда возникает ошибка при обработке сообщения, пытаться обработать его еще раз)?

Для этого и существует DLQ. Мы у себя как-то делали ретраи, но у нас была батчовая вычитка, и мы просто в новой транзакции ретраили по одному сообщению, если весь батч падал.

2024-04-14 14:40 UTC, SHvatov requested changes
@Nick-552 в целом все ок, но нужна доработка с обработкой ошибок десериализации. Отдельный лафк за тесты и использование анноташек спринга по максимуму)

2024-04-14 14:40 UTC, SHvatov commented on bot/src/test/java/edu/java/bot/kafka/LinkUpdatesKafkaListenerTest.java
> +//    @Test
в топку)

2024-04-14 20:31 UTC, Nick-552 commented
Добавил обработчик ошибок (в том числе ошибок десериализации).
Тут меня волнуют несколько моментов:
1) `@RetryableTopic`, который почему то влияет на обработку сообщений с ошибкой десериализации, хотя вроде бы на эту ошибку он даже не должен ретраить 
![image](https://github.com/Nick-552/link-tracker/assets/115263760/67ea7627-a1a9-4fa8-acea-b9d853ebf556)

2) То что теперь у нас вся обработка происходит в KafkaErrorHandler, в том числе тех ошибок, которые возникли внутри метода `@KafkaListener`. То есть исключения не попадают в метод `@DltHandler`

2024-04-21 17:31 UTC, SHvatov approved these changes

2025-03-01 19:29 UTC, merged